matrix:
  include:
  - os: linux
    language: python
    python: 3.7
    services:
    - xvfb
    before_install:
    - ulimit -n 65536
    - python --version
    - pip install --upgrade pip
    - export DISPLAY=:99.0
    after_success:
    - pip install .[docs]
    - "(cd docs && make html)"
    - bash <(curl -s https://codecov.io/bash) -v
  - os: windows
    language: shell
    before_install:
    - choco install python --version 3.7.5
    #- pip install pyinstaller
    #after_script:
    #- pyinstaller --clean --onefile --noconsole --paths C:\Windows\System32\downlevel
    #  Xi-cam.spec
    after_success:
    - bash <(curl -s https://codecov.io/bash) -v
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
env: TRAVIS=True
cache:
  apt: true
  pip: true
addons:
  apt:
    packages:
    - qtbase5-dev
before_install:
- python --version
install:
- pip install --upgrade attrs>=17.4.0
- pip install --upgrade setuptools wheel
- pip install .[pyqt5,tests,freeze]
script:
- 'pylint xicam --errors-only || :'
#- 'pytest --cov=xicam --cov-config=.coveragerc . || :'
- 'coverage run -m pytest .'
deploy:
  skip_cleanup: true
  provider: pypi
  username: "__token__"
  password:
    secure: "eIM9bybce/m0N5USAcLOQZ4cFVNocyWu66IuRzFMicpaWVuI1/GXtEo5P5Sq/eR8BVOgMR6Y638km74QE8SRlP45rAx80CjCPQ5IkDazGKB2k8h/s0kPdYfMQg2O0bRWBjCgzKN1gDhNtKggHSVzfn3chZHjyCOQov4g7AYAtWZbz6lRH4RORkoha5Ol3vZOSWs1St5wJlVZawVG7LRUt6fJ5G5q9hjt9bD3SFsk9pjb6PNSM6JVtp7uz6qP9vaBqWZaZ1k8qmkfFo7eJcu3ScBdBYcNSR7UmgvBnRiiXxwRXuQfBUmdAJ70NksDBeweyzV73AlbFrLW13cM7W9nOdLxHld7MSIJ0hePATTCNZS6RuOmlGX9Ix2dWN2uKFEphlIxK8437nJXQqvcVdBHDLKYipS5WCqmHwNCcb7YUNsKA0bBhzzHB6r37HidrQmH/25R16qxTproALL3W9IHrOtkW1yXdYJcCCIOQWjkBA2b8YQ9YmllHRTKRQoNk+WsiKKxyLU1StW8vNni3xbcMdK7FynCKXS+IOi09uEEiw0qyEpME8+Bp30DW2GCXQRIiD/zWpBc47FKkgN0ZaQNw9p8BuxsHMkSDESYsAlSZ5lPYDC0AbQJedBqyQ+YH3O0zaUkVm1urSEv5H0fpWmFK+yjVl4eV0Xy9hKt+dPfGus="
  distributions: sdist bdist_wheel bdist_egg
  #skip_existing: true
  on:
    tags: true
    os: linux
